### PR TITLE
Connect to device with adb_shell RSA key

### PR DESCRIPTION
**Pull request by develoopeer**
Adb_shell require rsa key for authorization.

### CODE REVIEW

**Comment by Alex-cyber64** [comment]
i have been trying to install it and have been giving me this problem, do you have an ways of solving;
┌──(alex-cyber㉿Attack)-[~]
└─$ pip3 install git+https://github.com/EntySec/Ghost
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/EntySec/Ghost
  Cloning https://github.com/EntySec/Ghost to /tmp/pip-req-build-_w4qzeai
  Running command git clone --filter=blob:none --quiet https://github.com/EntySec/Ghost /tmp/pip-req-build-_w4qzeai
  Resolved https://github.com/EntySec/Ghost to commit fc152e8325a21e47f54aa82801b63dbeeef703e9
  Preparing metadata (setup.py) ... done
Requirement already satisfied: adb-shell in ./.local/lib/python3.10/site-packages (from ghost==8.0.0) (0.4.2)
Requirement already satisfied: rsa in ./.local/lib/python3.10/site-packages (from adb-shell->ghost==8.0.0) (4.8)
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from adb-shell->ghost==8.0.0) (3.4.8)
Requirement already satisfied: pyasn1 in /usr/lib/python3/dist-packages (from adb-shell->ghost==8.0.0) (0.4.8)

**Comment by develoopeer** [comment]
I didn`t get ya. This PR is not merged to origin repository. If you want to install Ghost version of this PR, you need to copy code from all commits of this PR or install Ghost from my fork.
Just remove previous installed version and install new one from fork:
```shell
pip3 uninstall Ghost
pip3 install git+https://github.com/develoopeer/Ghost 
```

**Comment by Alex-cyber64** [comment]
Thanks a lot, i managed to install using your fork.
Also, i don't know if i don't know how to do or what. I am trying to read an android cellphone which is lost and found and locked remotely but it doesn't give owner's instructions or details. 

Now am trying to unlock it with ghost or any you can recommend.

**Comment by develoopeer** [comment]
If i got u right, u want to unlock your(not stolen or whatever) phone, via adb.
The easiest way is to return it to original settings via recovery, but all the data on device will be erased.
But if you want to try to bruteforce the password, to save your data, you may use [this one](https://github.com/urbanadventurer/Android-PIN-Bruteforce)

**Comment by Alex-cyber64** [comment]
i would like to try to brutalforce the password but i don't have USB OTG cable/adapter to connect on a locked phone and A Nethunter phone. if possible would like to use a computer to brutalforce the password.

As for settings via recovery i have tried but it doesn't allow me to go boot mode i don't if is because it was remotely locked. 

And also it requires usb debug  enable

**Comment by develoopeer** [comment]
U can boot in recovery mode by pressing some keys combination(like volume+/- plus power button). You need to Google this combination special for your device.

**Comment by Alex-cyber64** [comment]
IMG-1528

I have tried my friend, tried the keys Volume up + Power button but it doesn't take me to recovery mode. 

I think know one knows how to unlock a remote locked phone as it was locked with find my phone

**Comment by develoopeer** [comment]
I dont know how to help you.
[Find my Mobile](https://findmymobile.samsung.com/) is some special utility for samsung devices. You need to ask this question on any samsung forum, or in samsung technical support. They can help you.
All i can say, utilities based on adb(ghost rtc.) is not your choice.

**Comment by Alex-cyber64** [comment]
NO problem my friend thanks for your help lets keep on chatting if any assistance required

**Comment by Alex-cyber64** [comment]
Please try to work on the solution of braking this kind of security.

**Comment by enty8080** [comment]
@develoopeer It is merged now.

**Comment by develoopeer** [comment]
Haha, nice one. It`s finally happen

**Pull request merged**
